/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_avian_xvr_media_sapi_Sapi5Synthesizer */

#ifndef _Included_com_avian_xvr_media_sapi_Sapi5Synthesizer
#define _Included_com_avian_xvr_media_sapi_Sapi5Synthesizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_avian_xvr_media_sapi_Sapi5Synthesizer
 * Method:    synthToBuffer
 * Signature: (Ljava/lang/String;Lcom/avian/xvr/media/sapi/ISapiStreamHandler;)V
 */
JNIEXPORT void JNICALL Java_com_avian_xvr_media_sapi_Sapi5Synthesizer_synthToBuffer
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
